name: pre-commit
on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  ROS_DISTRO: humble

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code from current branch
      uses: actions/checkout@v4
    - name: Run pre-commit
      run: |
        pip3 install pre-commit
        source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
        pre-commit run --all-files